# ============================================================
# SPRING BOOT DEPLOY PIPELINE
# ------------------------------------------------------------
# This GitHub Actions workflow automates:
# 1. Pulls the latest Docker image from Docker Hub
# 2. Runs (or updates) the container on the target environment
# ============================================================
name: Spring Boot Deploy Pipeline

# ------------------------------------------------------------
# TRIGGERS
# - Runs when the build pipeline succeeds (on workflow_run)
# - OR manually via the workflow_dispatch event
# ------------------------------------------------------------

on:
  workflow_run:
    workflows: ["Spring Boot Build Pipeline"]
    types:
      - completed
  workflow_dispatch:                           # Manual trigger option
    inputs:
      image_tag:
        description: "Specify Docker image tag to deploy (optional)"
        required: false

# ------------------------------------------------------------
# GLOBAL ENVIRONMENT VARIABLES
# ------------------------------------------------------------
env:
  JAVA_VERSION: 21
  REGISTRY: docker.io                             # Docker registry to push images to
  GITHUB_REPOSITORY: ${{ github.repository }}     # Use the GitHub repository name as image name
  IMAGE_TAG: ${{ github.sha }}                    # Use commit SHA as a unique image tag
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    steps:
      # ------------------------------------------------------------
      # STEP 1: Set Up Docker Build Environment
      # ------------------------------------------------------------
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # ------------------------------------------------------------
      # STEP 2: Log In to Docker Hub
      # ------------------------------------------------------------
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_ACCESS_TOKEN }}

      # ------------------------------------------------------------
      # STEP 3: Pull the Docker Image
      # ------------------------------------------------------------
      - name: Pull Docker Image
        run: |
          echo "Pulling image from DockerHub: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.DEPLOY_TAG }}"
          docker pull ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.DEPLOY_TAG }}
          echo "Image pulled successfully"